steps:
  # This step uses a Node.js image to run npm commands
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # This is the deploy step to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - jotaah
      - '--source=.' # Deploy from the current directory
      - '--region=us-central1' # Replace with your region
      - '--allow-unauthenticated' # Or other settings
